#!/bin/bash
# Author: Sebastian Dohne <sed24@ic.ac.uk>
# Script: compile_latex.sh
# Description: Automates the process of compiling a LaTeX document with references, opens the resulting PDF, and cleans up intermediate files.
# Date: Oct 2024

#below is a shellscript that automates the process of compiling a LaTeX document with references, opens the resulting PDF, and cleans up intermediate files.

#Instructions: 

#Save this script in the same directory as your LaTeX and bibtex file. 
#If your LaTeX file is named mydocument.tex, can be run by passing this command the base name like so: bash CompileLaTeX.sh mydocument.tex

# % Removes the .tex extension if it's provided, otherwise uses the argument as-is
latexfile="${1%.tex}"

pdflatex "${latexfile}.tex" #Compiles the LaTeX document specified by $1 into a PDF for the first time. This generates intermediate files needed by bibtex.
bibtex "$latexfile" #Processes the bibliography using bibtex for the document specified by $1
pdflatex "${latexfile}.tex" #Compiles the document again (twice) to ensure all references and bibliography are correctly linked and cross references updated
pdflatex "${latexfile}.tex"
evince "${latexfile}.pdf" & #Opens the resulting PDF file in the background using the evince PDF viewer.


## Cleanup
rm -f *.aux *.log *.bbl *.blg
#Removes auxiliary files (.aux) that store cross-reference information.
#Removes log files (.log) with compilation details.
#Removes the bibliography file (.bbl) generated by bibtex.
#Removes bibtex log files (.blg)
#suppresses errors if the files don’t exist:
